/**
 * Generates `src/messages.gen.ts` (gitignored): the `Messages` type from `messages/vi/*.json`.
 * Run by the package `build` script, so turbo produces it before dependents typecheck.
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";

import { defaultLocale } from "../src/config";
import { compareKeys, packageDir, readCatalog } from "./catalog";

const catalog = await readCatalog();
const names = [...(catalog.get(defaultLocale)?.keys() ?? [])].sort(compareKeys);
const ident = (ns: string) => `ns_${ns.replace(/[^A-Za-z0-9_]/g, "_")}`;

const lines = [
  "// Generated by packages/i18n/scripts/gen-types.ts — do not edit.",
  ...names.map((ns) => `import type ${ident(ns)} from "../messages/${defaultLocale}/${ns}.json";`),
  "",
  "export type GeneratedMessages = {",
  ...names.map((ns) => `  ${JSON.stringify(ns)}: typeof ${ident(ns)};`),
  "};",
  "",
];

const target = path.join(packageDir, "src/messages.gen.ts");
await writeFile(target, lines.join("\n"), "utf8");
console.log(`i18n types: ${names.length} namespace(s) → ${path.relative(packageDir, target)}`);
