-- Generated by scripts/search-golden-sql.ts from supabase/tests/search_quality/{anchors,golden}.json.
-- Do not edit by hand: change the JSON files and regenerate (see scripts/search-quality.test.mjs).
begin;

select plan(2);

insert into auth.users (id, email) values
  ('00000000-0000-4000-8000-0000000000a1', 'perf-admin@example.com'),
  ('00000000-0000-4000-8000-0000000000b1', 'perf-viewer@example.com');

-- New profiles are guests until an allowlist entry says otherwise; the fixtures are internal users.
select set_config('request.jwt.claim.role', 'service_role', true);
update public.profiles set is_guest = false;
select set_config('request.jwt.claim.role', '', true);

insert into public.spaces (id, slug, name, visibility, created_by) values
  ('10000000-0000-4000-8000-000000000001', 'perf-1', 'perf-1', 'internal', '00000000-0000-4000-8000-0000000000a1');

insert into public.pages (id, space_id, position, title, created_by) values
  ('30000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000001', '0001', 'Quy trình nghỉ phép năm', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000002', '10000000-0000-4000-8000-000000000001', '0002', 'Chính sách làm việc từ xa', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000001', '0003', 'Hướng dẫn cài đặt VPN', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000004', '10000000-0000-4000-8000-000000000001', '0004', 'Quy định thanh toán công tác phí', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000005', '10000000-0000-4000-8000-000000000001', '0005', 'Cơ sở dữ liệu khách hàng', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000006', '10000000-0000-4000-8000-000000000001', '0006', 'Bảng phụ cấp theo cấp bậc', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000007', '10000000-0000-4000-8000-000000000001', '0007', 'Danh sách nhân sự phòng kỹ thuật', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000008', '10000000-0000-4000-8000-000000000001', '0008', 'Quy trình onboarding nhân viên mới', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000009', '10000000-0000-4000-8000-000000000001', '0009', 'Quy trình xử lý sự cố production', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-00000000000a', '10000000-0000-4000-8000-000000000001', '0010', 'Lịch trực on-call tháng này', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-00000000000b', '10000000-0000-4000-8000-000000000001', '0011', 'Hướng dẫn viết tài liệu kỹ thuật', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-00000000000c', '10000000-0000-4000-8000-000000000001', '0012', 'Mẫu hợp đồng lao động', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-00000000000d', '10000000-0000-4000-8000-000000000001', '0013', 'Chính sách bảo mật thông tin', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-00000000000e', '10000000-0000-4000-8000-000000000001', '0014', 'Kế hoạch đào tạo quý 4', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-00000000000f', '10000000-0000-4000-8000-000000000001', '0015', 'Biên bản họp tổng kết năm', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000010', '10000000-0000-4000-8000-000000000001', '0016', 'Thiết lập môi trường phát triển', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000011', '10000000-0000-4000-8000-000000000001', '0017', 'Quy định an toàn phòng cháy chữa cháy', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000012', '10000000-0000-4000-8000-000000000001', '0018', 'Đánh giá hiệu suất nhân viên', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000013', '10000000-0000-4000-8000-000000000001', '0019', 'Bảng giá dịch vụ vận chuyển', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000014', '10000000-0000-4000-8000-000000000001', '0020', 'Câu hỏi thường gặp về bảo hiểm xã hội', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000015', '10000000-0000-4000-8000-000000000001', '0021', 'Ghi chú nghỉ lễ Quốc khánh', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000016', '10000000-0000-4000-8000-000000000001', '0022', 'Hướng dẫn đặt phòng họp', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000017', '10000000-0000-4000-8000-000000000001', '0023', 'Quy trình mua sắm thiết bị', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000018', '10000000-0000-4000-8000-000000000001', '0024', 'Tổng quan kiến trúc hệ thống', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-000000000019', '10000000-0000-4000-8000-000000000001', '0025', 'Danh sách ngày nghỉ lễ trong năm', '00000000-0000-4000-8000-0000000000a1'),
  ('30000000-0000-4000-8000-00000000001a', '10000000-0000-4000-8000-000000000001', '0026', 'Quy trình nghỉ không lương', '00000000-0000-4000-8000-0000000000a1');

update public.page_documents as d set content_text = v.content_text, headings_text = v.headings_text, table_text = v.table_text
from (values
  ('30000000-0000-4000-8000-000000000001'::uuid, 'Nhân viên chính thức được nghỉ phép năm 12 ngày. Đăng ký nghỉ phép trên hệ thống nhân sự trước ít nhất 3 ngày làm việc. Quản lý trực tiếp duyệt đơn.', 'Điều kiện
Cách đăng ký', ''),
  ('30000000-0000-4000-8000-000000000002'::uuid, 'Nhân viên được làm việc từ xa tối đa hai ngày mỗi tuần sau khi hoàn thành thử việc. Cần thiết bị của công ty và kết nối an toàn.', 'Điều kiện áp dụng', ''),
  ('30000000-0000-4000-8000-000000000003'::uuid, 'Tải ứng dụng OpenVPN từ cổng nội bộ, nhập tên đăng nhập công ty và mã xác thực hai lớp để kết nối.', 'Windows
macOS', ''),
  ('30000000-0000-4000-8000-000000000004'::uuid, 'Chi phí đi lại, khách sạn và ăn uống khi đi công tác được hoàn ứng trong 5 ngày làm việc, kèm hóa đơn đỏ hợp lệ.', 'Hoàn ứng', ''),
  ('30000000-0000-4000-8000-000000000005'::uuid, 'Cơ sở dữ liệu khách hàng chạy trên PostgreSQL, sao lưu mỗi đêm lúc 2 giờ sáng và lưu giữ 30 ngày.', 'Sơ đồ bảng
Sao lưu', ''),
  ('30000000-0000-4000-8000-000000000006'::uuid, 'Tổng hợp các khoản phụ cấp hàng tháng.', '', 'Cấp bậc | Phụ cấp ăn trưa | Phụ cấp xăng xe
Nhân viên | 730.000 | 500.000
Trưởng nhóm | 730.000 | 800.000
Quản lý | 730.000 | 1.200.000'),
  ('30000000-0000-4000-8000-000000000007'::uuid, 'Danh sách cập nhật theo quý.', '', 'Mã | Họ tên | Chức danh
NV-20417 | Nguyễn Thị Thuỳ Dương | Kỹ sư backend
NV-20418 | Trần Quốc Đạt | Kỹ sư hạ tầng'),
  ('30000000-0000-4000-8000-000000000008'::uuid, 'Ngày đầu tiên nhân viên mới nhận laptop, tài khoản email và thẻ ra vào. Người hướng dẫn hỗ trợ trong ba tháng thử việc.', 'Tuần đầu tiên', ''),
  ('30000000-0000-4000-8000-000000000009'::uuid, 'Khi có sự cố production, người trực mở kênh sự cố, xác định mức độ SEV1 đến SEV3 và viết báo cáo hậu kiểm trong 48 giờ.', 'Phân loại mức độ
Báo cáo hậu kiểm', ''),
  ('30000000-0000-4000-8000-00000000000a'::uuid, 'Phân công người trực theo tuần, đổi ca cần báo trước một ngày.', '', ''),
  ('30000000-0000-4000-8000-00000000000b'::uuid, 'Tài liệu kỹ thuật cần có mục tiêu, phạm vi, ví dụ và danh sách thay đổi rõ ràng.', 'Cấu trúc bài viết', ''),
  ('30000000-0000-4000-8000-00000000000c'::uuid, 'Mẫu hợp đồng lao động xác định thời hạn và không xác định thời hạn, dùng cho nhân viên chính thức.', 'Điều khoản chung', ''),
  ('30000000-0000-4000-8000-00000000000d'::uuid, 'Không chia sẻ mật khẩu. Dữ liệu khách hàng thuộc loại bí mật, không lưu trên thiết bị cá nhân.', 'Mật khẩu
Thiết bị cá nhân', ''),
  ('30000000-0000-4000-8000-00000000000e'::uuid, 'Các khóa học nội bộ về kỹ năng mềm và an toàn thông tin trong quý 4.', '', ''),
  ('30000000-0000-4000-8000-00000000000f'::uuid, 'Cuộc họp tổng kết ghi nhận doanh thu tăng trưởng và kế hoạch cho năm tới.', 'Kết quả kinh doanh', ''),
  ('30000000-0000-4000-8000-000000000010'::uuid, 'Cài Node.js phiên bản mới, bật Docker và chạy lệnh khởi tạo dự án.', 'Cài đặt Node.js
Chạy Docker', ''),
  ('30000000-0000-4000-8000-000000000011'::uuid, 'Vị trí bình chữa cháy và lối thoát hiểm ở mỗi tầng.', '', ''),
  ('30000000-0000-4000-8000-000000000012'::uuid, 'Mỗi nửa năm quản lý đánh giá kết quả theo mục tiêu OKR đã thống nhất.', 'Chu kỳ đánh giá
Thang điểm OKR', ''),
  ('30000000-0000-4000-8000-000000000013'::uuid, 'Giá cước theo trọng lượng và khu vực.', '', 'Khu vực | Dưới 1kg | Mỗi 0,5kg tiếp theo
Nội thành | 15.000 | 2.500
Liên tỉnh | 32.000 | 5.000'),
  ('30000000-0000-4000-8000-000000000014'::uuid, 'Người lao động đóng bảo hiểm xã hội theo tỷ lệ quy định trên mức lương đóng bảo hiểm.', 'Mức đóng
Chế độ thai sản', ''),
  ('30000000-0000-4000-8000-000000000015'::uuid, 'Lịch nghỉ lễ Quốc khánh và lịch làm bù.', '', ''),
  ('30000000-0000-4000-8000-000000000016'::uuid, 'Đặt phòng họp trên lịch chung, mỗi lần tối đa hai giờ.', '', ''),
  ('30000000-0000-4000-8000-000000000017'::uuid, 'Đề xuất mua sắm thiết bị cần ba báo giá và được trưởng phòng phê duyệt.', 'Phê duyệt
Nhà cung cấp', ''),
  ('30000000-0000-4000-8000-000000000018'::uuid, 'Hệ thống gồm cổng web, dịch vụ cộng tác thời gian thực và cơ sở dữ liệu.', '', ''),
  ('30000000-0000-4000-8000-000000000019'::uuid, 'Các ngày nghỉ lễ theo quy định của nhà nước.', '', ''),
  ('30000000-0000-4000-8000-00000000001a'::uuid, 'Nghỉ phép không lương tối đa 30 ngày mỗi năm khi được quản lý đồng ý. Lương không được tính trong thời gian này.', '', '')
) as v (page_id, content_text, headings_text, table_text)
where d.page_id = v.page_id;

set local role authenticated;
select set_config('request.jwt.claim.sub', '00000000-0000-4000-8000-0000000000b1', true);

-- Mean reciprocal rank of the first relevant page within the top 10.
select cmp_ok(
  (
    select avg(x.rr)
    from (values
    ('g01', 'nghi phep nam', array['30000000-0000-4000-8000-000000000001']::uuid[]),
    ('g02', 'quy trình nghỉ phép năm', array['30000000-0000-4000-8000-000000000001']::uuid[]),
    ('g03', 'nghỉ phép', array['30000000-0000-4000-8000-000000000001', '30000000-0000-4000-8000-00000000001a']::uuid[]),
    ('g04', 'lam viec tu xa', array['30000000-0000-4000-8000-000000000002']::uuid[]),
    ('g05', '"làm việc từ xa"', array['30000000-0000-4000-8000-000000000002']::uuid[]),
    ('g06', 'vpn', array['30000000-0000-4000-8000-000000000003']::uuid[]),
    ('g07', 'cai dat vpn windows', array['30000000-0000-4000-8000-000000000003']::uuid[]),
    ('g08', 'hoan ung cong tac', array['30000000-0000-4000-8000-000000000004']::uuid[]),
    ('g09', 'cong tac phi', array['30000000-0000-4000-8000-000000000004']::uuid[]),
    ('g10', 'co so du lieu khach hang', array['30000000-0000-4000-8000-000000000005']::uuid[]),
    ('g11', 'sao luu postgresql', array['30000000-0000-4000-8000-000000000005']::uuid[]),
    ('g12', 'phu cap xang xe truong nhom', array['30000000-0000-4000-8000-000000000006']::uuid[]),
    ('g13', 'NV-20418', array['30000000-0000-4000-8000-000000000007']::uuid[]),
    ('g14', 'thuy duong', array['30000000-0000-4000-8000-000000000007']::uuid[]),
    ('g15', 'onboarding', array['30000000-0000-4000-8000-000000000008']::uuid[]),
    ('g16', 'nhan vien moi', array['30000000-0000-4000-8000-000000000008']::uuid[]),
    ('g17', 'su co production', array['30000000-0000-4000-8000-000000000009']::uuid[]),
    ('g18', 'sev1', array['30000000-0000-4000-8000-000000000009']::uuid[]),
    ('g19', 'bao cao hau kiem', array['30000000-0000-4000-8000-000000000009']::uuid[]),
    ('g20', 'lich truc', array['30000000-0000-4000-8000-00000000000a']::uuid[]),
    ('g21', 'tai lieu ky thuat', array['30000000-0000-4000-8000-00000000000b']::uuid[]),
    ('g22', 'hop dong lao dong', array['30000000-0000-4000-8000-00000000000c']::uuid[]),
    ('g23', 'bao mat thong tin', array['30000000-0000-4000-8000-00000000000d']::uuid[]),
    ('g24', 'mat khau', array['30000000-0000-4000-8000-00000000000d']::uuid[]),
    ('g25', 'quy trinh nghi phpe', array['30000000-0000-4000-8000-000000000001']::uuid[]),
    ('g26', 'kien truc he th', array['30000000-0000-4000-8000-000000000018']::uuid[]),
    ('g27', 'bang gia van chuyen', array['30000000-0000-4000-8000-000000000013']::uuid[]),
    ('g28', 'bao hiem xa hoi', array['30000000-0000-4000-8000-000000000014']::uuid[]),
    ('g29', 'nghỉ phép -lương', array['30000000-0000-4000-8000-000000000001']::uuid[]),
    ('g30', 'dat phong hop', array['30000000-0000-4000-8000-000000000016']::uuid[])
    ) as g (id, q, expected)
    cross join lateral (
      select coalesce(1.0 / min(r.n), 0) as rr
      from (
        select s.page_id, row_number() over () as n from public.search_pages(g.q, null, 10, 0) as s
      ) as r
      where r.page_id = any (g.expected)
    ) as x
  )::numeric,
  '>=',
  0.8::numeric,
  'golden set: MRR >= 0.8 on the anchor corpus'
);

-- Excluded / unwanted pages never show up.
select is(
  (
    select count(*)::integer
    from (values
    ('nghỉ phép -lương', array['30000000-0000-4000-8000-00000000001a']::uuid[])
    ) as f (q, forbidden)
    cross join lateral public.search_pages(f.q, null, 10, 0) as s
    where s.page_id = any (f.forbidden)
  ),
  0,
  'golden set: forbidden pages are not returned'
);

select * from finish();
rollback;
