// Generates supabase/tests/search_quality/golden.test.sql: a pgTAP quality gate that runs the 30
// golden queries (MRR >= 0.8, no "forbid" page in results) on the small anchor corpus, so a ranking
// regression fails `pnpm db:test` in CI. The 20k-page benchmark (scripts/search-bench.ts) is run by hand.
//
//   node scripts/search-golden-sql.ts > supabase/tests/search_quality/golden.test.sql
//
// scripts/search-quality.test.mjs fails when the committed file is out of date.

import { ADMIN_ID, ANCHOR_SPACE_ID, VIEWER_ID, anchorId, loadAnchors } from "./seed-perf.ts";
import { MRR_TARGET, TOP_K, loadGolden, queryText } from "./search-bench.ts";

const lit = (s: string): string => `'${s.replace(/'/g, "''")}'`;

export function buildGoldenPgTap(): string {
  const anchors = loadAnchors();
  const golden = loadGolden();
  const rows = golden
    .map(
      (g) =>
        `    (${lit(g.id)}, ${lit(queryText(g))}, array[${g.expect.map((k) => lit(anchorId(k))).join(", ")}]::uuid[])`,
    )
    .join(",\n");
  const forbidRows = golden
    .filter((g) => (g.forbid ?? []).length > 0)
    .map(
      (g) =>
        `    (${lit(queryText(g))}, array[${(g.forbid ?? []).map((k) => lit(anchorId(k))).join(", ")}]::uuid[])`,
    )
    .join(",\n");

  return `-- Generated by scripts/search-golden-sql.ts from supabase/tests/search_quality/{anchors,golden}.json.
-- Do not edit by hand: change the JSON files and regenerate (see scripts/search-quality.test.mjs).
begin;

select plan(2);

insert into auth.users (id, email) values
  (${lit(ADMIN_ID)}, 'perf-admin@example.com'),
  (${lit(VIEWER_ID)}, 'perf-viewer@example.com');

-- New profiles are guests until an allowlist entry says otherwise; the fixtures are internal users.
select set_config('request.jwt.claim.role', 'service_role', true);
update public.profiles set is_guest = false;
select set_config('request.jwt.claim.role', '', true);

insert into public.spaces (id, slug, name, visibility, created_by) values
  (${lit(ANCHOR_SPACE_ID)}, 'perf-1', 'perf-1', 'internal', ${lit(ADMIN_ID)});

insert into public.pages (id, space_id, position, title, created_by) values
${anchors.map((a, i) => `  (${lit(anchorId(a.key))}, ${lit(ANCHOR_SPACE_ID)}, ${lit(String(i + 1).padStart(4, "0"))}, ${lit(a.title)}, ${lit(ADMIN_ID)})`).join(",\n")};

update public.page_documents as d set content_text = v.content_text, headings_text = v.headings_text, table_text = v.table_text
from (values
${anchors.map((a) => `  (${lit(anchorId(a.key))}::uuid, ${lit(a.content)}, ${lit(a.headings)}, ${lit(a.table)})`).join(",\n")}
) as v (page_id, content_text, headings_text, table_text)
where d.page_id = v.page_id;

set local role authenticated;
select set_config('request.jwt.claim.sub', ${lit(VIEWER_ID)}, true);

-- Mean reciprocal rank of the first relevant page within the top ${TOP_K}.
select cmp_ok(
  (
    select avg(x.rr)
    from (values
${rows}
    ) as g (id, q, expected)
    cross join lateral (
      select coalesce(1.0 / min(r.n), 0) as rr
      from (
        select s.page_id, row_number() over () as n from public.search_pages(g.q, null, ${TOP_K}, 0) as s
      ) as r
      where r.page_id = any (g.expected)
    ) as x
  )::numeric,
  '>=',
  ${MRR_TARGET}::numeric,
  'golden set: MRR >= ${MRR_TARGET} on the anchor corpus'
);

-- Excluded / unwanted pages never show up.
select is(
  (
    select count(*)::integer
    from (values
${forbidRows}
    ) as f (q, forbidden)
    cross join lateral public.search_pages(f.q, null, ${TOP_K}, 0) as s
    where s.page_id = any (f.forbidden)
  ),
  0,
  'golden set: forbidden pages are not returned'
);

select * from finish();
rollback;
`;
}

import { fileURLToPath } from "node:url";
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  process.stdout.write(buildGoldenPgTap());
}
